name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
  merge_group:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RUSTFLAGS="--deny warnings" cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  check-format:
    name: check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --check

  all-jobs-succeed:
    name: All checks succeeded
    if: success()
    runs-on: ubuntu-latest
    needs: [clippy, test, check-format]
    steps:
      - name: Mark the job as successful
        run: exit 0
